
project_id = "prj_DqQJgGRkFLBE9yyWdWHyfCkb"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080", "https://id-preview--43e185ae-7acc-4409-a1dd-9f797f2704f0.lovable.app"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = true
enable_confirmations = true

[analytics]
enabled = false

[functions]
[functions.openai-chat]
verify_jwt = false
