// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhndizppvyufvbejkqzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobmRpenBwdnl1ZnZiZWprcXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTEwNjQsImV4cCI6MjA1Nzc2NzA2NH0.L5bGoyZs0ZY5dRQPV53fLBk_ieJDtwB979W3Iq4T5tY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);